export const FETCH_LEAGUES_SUCCESS = "FETCH_LEAGUES_SUCCESS";

export const FETCH_LEAGUES_START = "FETCH_LEAGUES_START";
export const FETCH_LEAGUES_Failed = "FETCH_LEAGUES_Failed";

export const FETCH_LEAGUE_DETAILS_SUCCESS = "FETCH_LEAGUE_DETAILS_SUCCESS";

export const FETCH_TEAM_DETAILS_SUCCESS = "FETCH_TEAM_DETAILS_SUCCESS";

export const FETCH_TEAMS_LEAGUE_SUCCESS = "FETCH_TEAMS_LEAGUE_SUCCESS";
export const FETCH_TEAMS_LEAGUE_START = " FETCH_TEAMS_LEAGUE_START";

export const FETCH_TEAMS_LEAGUE_FAILED = " FETCH_TEAMS_LEAGUE_FAILED";

export const FETCH_TEAM_DETAILS_START = " FETCH_TEAM_DETAILS_START";

export const FETCH_TEAM_DETAILS_FAILED = " FETCH_TEAM_DETAILS_FAILED";
